# Generated by Django 2.1.1 on 2018-10-31 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secondpage',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='productDetail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='productWork',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
