# Generated by Django 2.1.1 on 2018-11-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181031_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='productWork',
            field=models.CharField(max_length=200),
        ),
    ]
